import { createFileRoute, notFound } from "@tanstack/react-router";
import { ServicePage, type ServicePageData } from "@/components/ServicePage";
import { SERVICES } from "@/lib/services-data";

const PAGES: Record<string, ServicePageData> = {
  "cyber-risk": {
    slug: "cyber-risk",
    heroTitle: "Know Your Risk. Before Your Adversaries Do.",
    heroSubtext:
      "Fortress delivers enterprise cyber risk programs combining senior advisory judgment with AI-assisted analytics — giving your leadership team the risk clarity needed to make confident decisions.",
    overview: [
      "Cyber risk is no longer just a technical problem — it is a board-level strategic concern. Organizations across the GCC face an expanding threat surface, rising regulatory expectations, and adversaries who move faster than traditional security programs can respond. Fortress was built to close that gap.",
      "Our AI-Enhanced Cyber Risk service combines structured enterprise risk assessments with machine-assisted vulnerability analysis, delivering findings that are validated by senior advisors — not generated by tools alone. Every engagement is led by practitioners who have operated inside enterprise environments and understand how risk translates to business impact.",
      "We assess your environment against recognized frameworks, benchmark your maturity against industry peers, and deliver a prioritized remediation roadmap that your team can actually execute. Our risk governance layer ensures findings reach the right stakeholders — from technical teams to the C-suite and board.",
      "Engagements are scoped to your organization's size, sector, and regulatory context. Whether you are preparing for a regulatory review, responding to a board mandate, or building a risk program from the ground up, Fortress delivers the structure and the substance.",
    ],
    capabilities: [
      "Enterprise cyber risk assessments",
      "AI-assisted vulnerability scanning",
      "Red-team penetration testing (via Wattlecorp)",
      "Resilience scoring models",
      "Cyber maturity benchmarking",
      "Risk governance framework design",
      "Executive risk reporting",
      "Regulatory alignment review",
    ],
    approach: [
      {
        title: "Assess",
        description:
          "We map your asset landscape, threat exposure, and existing controls using a structured methodology aligned to NIST CSF and ISO 27001. AI tooling accelerates data collection; senior advisors validate every finding.",
      },
      {
        title: "Analyze & Benchmark",
        description:
          "Risk findings are scored, prioritized by business impact, and benchmarked against sector peers. We identify critical gaps and model exposure scenarios relevant to your operating environment.",
      },
      {
        title: "Advise & Govern",
        description:
          "We deliver a board-ready risk report, a technical remediation roadmap, and a governance framework that embeds risk visibility into your ongoing security operations.",
      },
    ],
    deliverables: [
      {
        title: "AI-Assisted Cyber Risk Assessment Report",
        description:
          "A comprehensive report documenting risk findings across your environment, prioritized by likelihood and business impact, with a structured remediation roadmap for technical and executive audiences.",
      },
      {
        title: "Enterprise Vulnerability Scan Results",
        description:
          "Validated vulnerability findings from AI-assisted scanning, reviewed and contextualized by senior advisors to eliminate noise and surface what actually matters.",
      },
      {
        title: "Cyber Maturity Benchmarking Dashboard",
        description:
          "A visual dashboard positioning your organization's security maturity against industry standards and GCC sector peers, with gap analysis and improvement pathways.",
      },
      {
        title: "Risk Governance & Resilience Framework",
        description:
          "A documented framework for ongoing risk oversight, including ownership assignments, escalation thresholds, board reporting templates, and resilience scoring criteria.",
      },
    ],
    audiences: [
      {
        description:
          "CISOs at regulated financial institutions, energy firms, or government-linked entities who need a structured, defensible risk assessment to present to their board or regulator — not another tool-generated scan report.",
      },
      {
        description:
          "CEOs and COOs at mid-to-large enterprises entering new markets or undergoing digital transformation who need to understand their expanding cyber exposure before committing capital or operations.",
      },
      {
        description:
          "Risk and compliance officers who have inherited a fragmented security program and need an independent, authoritative baseline assessment to prioritize investment and demonstrate due diligence.",
      },
    ],
    differentiators: [
      {
        title: "Senior-Led, Not Tool-Led",
        description:
          "Every assessment is directed by experienced practitioners. AI accelerates the process; human judgment owns the output.",
      },
      {
        title: "Decision-Grade Risk Reporting",
        description:
          "Our deliverables are structured for executive and board consumption — not just technical teams. Risk findings translate directly to business language.",
      },
      {
        title: "GCC Context Built In",
        description:
          "Our advisors understand the regulatory, geopolitical, and sector-specific risk environment across the Gulf — giving benchmarks and recommendations real regional relevance.",
      },
    ],
    relatedSlugs: ["grc", "intelligence-monitoring", "risk-assessment"],
  },

  grc: {
    slug: "grc",
    heroTitle: "Build the Controls. Earn the Confidence.",
    heroSubtext:
      "Fortress designs and implements end-to-end GRC programs that align your policies, controls, and audit posture with international frameworks and regional regulatory expectations.",
    overview: [
      "Regulatory pressure across the GCC is accelerating. Whether you operate under SAMA, NESA, ADIO, or are pursuing ISO 27001 certification, the expectation is clear: governance must be documented, controls must be tested, and audit readiness must be continuous — not periodic.",
      "Fortress GRC engagements are built around your specific regulatory obligations, industry sector, and organizational maturity. We do not deliver generic policy templates — we design control frameworks that reflect how your organization actually operates and what your regulators actually expect to see.",
      "Our advisory team brings deep experience across ISO 27001, NIST CSF, NCA ECC, SAMA CSF, and related frameworks. We work alongside your internal teams to build programs that are sustainable — not dependent on external consultants to maintain.",
      "Third-party and vendor risk is an increasingly critical component of enterprise GRC. We design vendor evaluation frameworks and third-party risk programs that give your organization visibility into supply-chain exposure before it becomes a liability.",
    ],
    capabilities: [
      "Policy and control framework design",
      "Regulatory compliance advisory",
      "ISO 27001 / NIST / NCA ECC alignment",
      "Third-party and vendor risk programs",
      "Internal audit support and readiness",
      "Compliance gap assessments",
      "Control testing and evidence management",
      "Board and executive governance reporting",
    ],
    approach: [
      {
        title: "Gap Assessment",
        description:
          "We conduct a structured gap analysis against your target framework (ISO 27001, NIST, SAMA CSF, or NCA ECC), documenting current-state controls, missing documentation, and compliance shortfalls with prioritized remediation actions.",
      },
      {
        title: "Design & Implement",
        description:
          "We design the policy architecture, control procedures, and governance structures needed to close identified gaps — and work with your team to implement them in a way that fits your operational reality.",
      },
      {
        title: "Audit Readiness & Ongoing Support",
        description:
          "We prepare your organization for internal or external audit, support evidence collection, and provide ongoing advisory to maintain compliance posture as your environment evolves.",
      },
    ],
    deliverables: [
      {
        title: "Governance & Control Framework",
        description:
          "A complete policy and procedure library, control ownership matrix, and governance structure document tailored to your regulatory obligations and operational context.",
      },
      {
        title: "Regulatory Compliance Gap Assessment",
        description:
          "A detailed gap analysis report mapping your current posture against the target framework, with a prioritized action plan and remediation timeline.",
      },
      {
        title: "Third-Party Risk Management Program",
        description:
          "A structured vendor evaluation and ongoing monitoring framework, including risk questionnaires, scoring models, and escalation procedures.",
      },
      {
        title: "ISO 27001 / NIST Alignment & Audit Readiness Report",
        description:
          "A framework alignment report with evidence mapping, outstanding requirements, and a readiness checklist for certification or regulatory review.",
      },
    ],
    audiences: [
      {
        description:
          "Compliance officers at financial institutions, telecoms, or critical infrastructure operators facing SAMA, NCA, or NESA regulatory reviews who need a structured, evidence-backed compliance program — not a checklist.",
      },
      {
        description:
          "CISOs and legal teams at multinational enterprises operating across GCC jurisdictions who need to reconcile multiple overlapping regulatory frameworks into a single coherent governance structure.",
      },
      {
        description:
          "Boards and executive teams at organizations preparing for ISO 27001 certification or responding to a failed audit who need rapid, expert-led remediation and audit preparation support.",
      },
    ],
    differentiators: [
      {
        title: "Regional Regulatory Depth",
        description:
          "Our advisors have direct experience with GCC regulatory frameworks including SAMA CSF, NCA ECC, and NESA — not just international standards.",
      },
      {
        title: "Programs Built to Last",
        description:
          "We design governance structures your team can own and maintain. We build internal capability, not dependency.",
      },
      {
        title: "End-to-End Coverage",
        description:
          "From policy design through audit support, we manage the full GRC lifecycle in a single, coordinated engagement.",
      },
    ],
    relatedSlugs: [
      "cyber-risk",
      "security-architecture",
      "risk-assessment",
    ],
  },

  "security-architecture": {
    slug: "security-architecture",
    heroTitle: "Architecture That Holds. Strategy That Scales.",
    heroSubtext:
      "Fortress designs forward-looking security architectures aligned to enterprise transformation, cloud adoption, and M&A activity — built to protect what you are building next, not just what exists today.",
    overview: [
      "Most organizations inherit their security architecture — it was built incrementally, reactively, and without a unifying strategy. As enterprises in the GCC accelerate cloud adoption, pursue acquisitions, and modernize critical infrastructure, that inherited architecture becomes a liability.",
      "Fortress Security Architecture & Strategy engagements start with your business direction. We assess where your organization is going — not just where it is — and design a security architecture that supports that trajectory. Our work spans enterprise security strategy, cloud and hybrid infrastructure, Zero Trust design, identity and access architecture, and OT/ICS environments.",
      "We operate at the intersection of strategy and execution. Our advisors work with your technology and business leaders to translate strategic priorities into actionable security architecture decisions — and then support implementation through trusted technical partners.",
      "For organizations navigating M&A activity, we provide security due diligence and post-merger architecture integration advisory — ensuring that acquired entities don't introduce unmanaged risk into your environment.",
    ],
    capabilities: [
      "Enterprise security strategy design",
      "Cloud & hybrid infrastructure security architecture",
      "Zero Trust architecture and implementation roadmap",
      "Identity & access management (IAM) architecture",
      "OT / ICS security advisory",
      "M&A security due diligence",
      "Digital transformation security alignment",
      "Architecture review and gap assessment",
    ],
    approach: [
      {
        title: "Assess & Align",
        description:
          "We review your existing architecture, understand your business strategy and transformation roadmap, and identify the gaps, dependencies, and risks in your current security posture relative to where you are heading.",
      },
      {
        title: "Design",
        description:
          "We produce a target-state security architecture aligned to your strategic direction — covering network segmentation, cloud security, identity, access, and OT environments — with a phased implementation roadmap.",
      },
      {
        title: "Execute & Govern",
        description:
          "We support implementation planning, vendor selection, and architecture governance — ensuring decisions are made consistently and that the architecture evolves as your business does.",
      },
    ],
    deliverables: [
      {
        title: "Enterprise Security Strategy & Transformation Roadmap",
        description:
          "A strategic document mapping your current security posture to a target state, with a phased transformation plan, investment priorities, and executive-level narrative.",
      },
      {
        title: "Cloud & Infrastructure Security Architecture Blueprint",
        description:
          "A detailed architecture reference covering your cloud and hybrid environment security controls, segmentation design, and technology recommendations.",
      },
      {
        title: "Zero Trust & IAM Design Framework",
        description:
          "A Zero Trust architecture design and identity governance framework, including access policy models, authentication requirements, and implementation guidance.",
      },
      {
        title: "OT/ICS Security Advisory Assessment",
        description:
          "A risk and architecture assessment of your operational technology environment with sector-appropriate security recommendations and a risk mitigation plan.",
      },
    ],
    audiences: [
      {
        description:
          "CTOs and CISOs at enterprises undergoing large-scale cloud migration or digital transformation who need a security architecture designed for their future state — not retrofitted onto legacy infrastructure.",
      },
      {
        description:
          "Corporate development and security teams at organizations pursuing acquisitions or mergers who need security due diligence and post-merger integration architecture advisory.",
      },
      {
        description:
          "CISOs at energy, utilities, or industrial organizations who operate hybrid IT/OT environments and need specialized advisory on securing operational technology without disrupting critical operations.",
      },
    ],
    differentiators: [
      {
        title: "Strategy Before Technology",
        description:
          "We start with your business direction. Architecture decisions follow strategy, not vendor preference or default configurations.",
      },
      {
        title: "IT and OT Expertise",
        description:
          "Few advisory firms can credibly address both enterprise IT architecture and operational technology security. Fortress does both.",
      },
      {
        title: "Implementation-Ready Outputs",
        description:
          "Our architecture deliverables are designed to hand off to your technical teams or implementation partners — not sit on a shelf.",
      },
    ],
    relatedSlugs: ["cyber-risk", "grc", "intelligence-monitoring"],
  },

  "intelligence-monitoring": {
    slug: "intelligence-monitoring",
    heroTitle: "See the Threat Before It Arrives.",
    heroSubtext:
      "Fortress delivers an always-on intelligence capability — combining geopolitical analysis, AI-driven threat monitoring, and supply-chain risk surveillance to keep your leadership informed and your defenses ahead.",
    overview: [
      "The threat landscape facing GCC enterprises is not limited to technical vulnerabilities. Geopolitical shifts, sanctions changes, threat actor campaigns, and supply-chain disruptions all carry direct security and business implications — and most organizations have no structured capability to monitor them.",
      "Fortress Intelligence & Risk Monitoring is an ongoing advisory service, not a point-in-time report. We combine open-source and commercial intelligence sources with AI-driven monitoring tooling and senior analyst review to deliver intelligence products that are relevant, timely, and actionable for your sector and geography.",
      "Our weekly intelligence briefs are written for executive and board audiences — not security operations teams. They translate threat developments, regulatory changes, and geopolitical shifts into business-relevant risk language that supports decision-making at the highest level.",
      "Supply-chain and third-party exposure is a growing intelligence priority. We monitor your key vendors, partners, and critical dependencies for emerging risk signals — giving you early warning before an exposure becomes an incident.",
    ],
    capabilities: [
      "Weekly geopolitical & emerging risk briefings",
      "AI-driven threat actor monitoring",
      "Supply chain and third-party risk intelligence",
      "Threat actor tracking and profiling",
      "Sanctions and regulatory change monitoring",
      "Dark web and open-source intelligence collection",
      "Sector-specific threat landscape analysis",
      "Executive intelligence reporting",
    ],
    approach: [
      {
        title: "Baseline & Profile",
        description:
          "We establish your intelligence requirements: key assets, critical third parties, geographies of operation, sector threat landscape, and executive risk appetite. This baseline shapes everything we monitor and report.",
      },
      {
        title: "Continuous Collection & Analysis",
        description:
          "Our team runs continuous AI-assisted monitoring across threat feeds, geopolitical sources, regulatory channels, and supply-chain signals — with senior analyst review to separate noise from genuine risk.",
      },
      {
        title: "Intelligence Delivery",
        description:
          "Weekly briefs, on-demand alerts for high-priority developments, and quarterly strategic threat reviews delivered in formats calibrated to your executive team's needs and decision cadence.",
      },
    ],
    deliverables: [
      {
        title: "Weekly Geopolitical & Emerging Risk Intelligence Brief",
        description:
          "A curated, senior-analyst-authored brief covering the week's most relevant geopolitical developments, threat actor activity, and regulatory changes — written for executive and board audiences.",
      },
      {
        title: "Supply Chain Risk Monitoring Report",
        description:
          "A monthly report covering risk signals from your critical vendors and supply-chain partners, including sanctions exposure, operational disruptions, and emerging third-party vulnerabilities.",
      },
      {
        title: "Threat Actor Tracking Dashboard",
        description:
          "An ongoing intelligence product profiling threat actors relevant to your sector and geography, tracking their tools, techniques, targets, and recent activity.",
      },
      {
        title: "AI-Driven Threat & Regulatory Risk Monitoring Summary",
        description:
          "A consolidated monthly summary of AI-flagged risk signals across threat, regulatory, and geopolitical domains, validated by senior analysts and prioritized by relevance to your environment.",
      },
    ],
    audiences: [
      {
        description:
          "CEOs and board members at GCC-based enterprises who need structured geopolitical and threat intelligence delivered in executive language — not SIEM alerts or technical feeds that require a security analyst to interpret.",
      },
      {
        description:
          "Risk and strategy officers at organizations with significant cross-border operations, supply-chain dependencies, or exposure to sanctioned jurisdictions who need continuous monitoring of the regulatory and threat environment.",
      },
      {
        description:
          "CISOs who have a mature internal security operations capability but lack the geopolitical and strategic intelligence layer needed to contextualize technical threats within the broader risk picture.",
      },
    ],
    differentiators: [
      {
        title: "Executive-Grade Intelligence",
        description:
          "Our intelligence products are written for decision-makers. We translate complex threat and geopolitical dynamics into clear, actionable risk language.",
      },
      {
        title: "GCC and Regional Focus",
        description:
          "Our intelligence team has deep familiarity with the Gulf's geopolitical landscape, regulatory environment, and sector-specific threat actors — giving our analysis genuine regional relevance.",
      },
      {
        title: "Always On",
        description:
          "This is not a quarterly report. It is a continuous monitoring service with weekly outputs and on-demand escalation when high-priority threats emerge.",
      },
    ],
    relatedSlugs: ["cyber-risk", "incident-advisory", "grc"],
  },

  "incident-advisory": {
    slug: "incident-advisory",
    heroTitle: "When It Matters Most, We Are There.",
    heroSubtext:
      "Fortress provides trusted, executive-level counsel from first detection through containment, recovery, and lessons-learned — ensuring your organization responds with clarity, not chaos.",
    overview: [
      "A cyber incident is not a technical problem — it is an organizational crisis. How your leadership responds in the first hours and days determines the operational, reputational, and regulatory outcome. Most organizations are not prepared to manage that response at the executive level.",
      "Fortress Incident Advisory & Crisis Management provides senior advisory support at every stage of an incident — from the moment of detection through executive decision-making during active response, board and regulator communications, post-incident recovery, and the lessons-learned process that prevents recurrence.",
      "We work alongside your internal teams and technical response partners — not instead of them. Our role is to ensure that executive decisions are made with accurate, timely information; that communications to boards, regulators, and the public are handled with precision; and that the organization emerges from the incident with its posture stronger than before.",
      "Before incidents occur, we help organizations prepare through tabletop exercises and crisis simulations that test the executive response capability — not just the technical one. The goal is to ensure that when a real incident happens, your leadership team has already made the hard decisions once.",
    ],
    capabilities: [
      "Executive incident response advisory",
      "Cyber crisis decision support",
      "Board and regulator communications",
      "Post-incident recovery planning",
      "Tabletop exercises and executive simulations",
      "Crisis playbook design",
      "Lessons-learned and root cause advisory",
      "Incident timeline reconstruction",
    ],
    approach: [
      {
        title: "Detect & Advise",
        description:
          "From the moment of notification, Fortress advisors provide structured decision support to your executive team — helping you assess the situation, prioritize containment actions, and establish a clear command structure for the response.",
      },
      {
        title: "Manage & Communicate",
        description:
          "We guide communications to your board, regulators, legal counsel, and — where required — the public, ensuring that every statement is accurate, defensible, and appropriate to the evolving situation.",
      },
      {
        title: "Recover & Strengthen",
        description:
          "Once the incident is contained, we lead the recovery and lessons-learned process — documenting what happened, why it happened, and what structural changes are needed to prevent recurrence.",
      },
    ],
    deliverables: [
      {
        title: "Executive Incident Response Advisory",
        description:
          "Real-time senior advisory support during an active incident, including situation assessment, decision facilitation, escalation guidance, and coordination with technical response teams.",
      },
      {
        title: "Cyber Crisis Management Playbook",
        description:
          "A pre-built, organization-specific crisis playbook defining roles, decision authorities, communication protocols, and response procedures — ready to activate before an incident occurs.",
      },
      {
        title: "Tabletop Exercise & Simulation Report",
        description:
          "A post-exercise report documenting scenario findings, executive response gaps, decision-point analysis, and recommended improvements to your incident response capability.",
      },
      {
        title: "Post-Incident Recovery & Lessons-Learned Assessment",
        description:
          "A comprehensive post-incident review documenting the timeline, root cause, response effectiveness, and a structured remediation roadmap to address identified gaps.",
      },
    ],
    audiences: [
      {
        description:
          "CEOs and executive leadership teams at organizations that have experienced — or narrowly avoided — a significant cyber incident and recognize that their response capability is not prepared for the next one.",
      },
      {
        description:
          "CISOs and general counsel at regulated entities in financial services, energy, or critical infrastructure who face mandatory regulatory notification requirements and need expert guidance on how to manage communications without creating legal or regulatory liability.",
      },
      {
        description:
          "Boards and audit committees who want to test their organization's crisis response capability through a structured executive tabletop exercise before a real incident forces the test upon them.",
      },
    ],
    differentiators: [
      {
        title: "Executive-Level, Not Technical-Only",
        description:
          "We operate at the leadership layer. Our advisors help executives make decisions — not just help technical teams execute them.",
      },
      {
        title: "Communications Expertise",
        description:
          "Board, regulator, and public communications during a cyber crisis require precision. We have managed these communications in high-stakes, high-visibility environments.",
      },
      {
        title: "Before, During, and After",
        description:
          "From pre-incident preparation through post-incident recovery, Fortress provides continuous advisory across the full incident lifecycle.",
      },
    ],
    relatedSlugs: ["intelligence-monitoring", "cyber-risk", "grc"],
  },

  "risk-assessment": {
    slug: "risk-assessment",
    heroTitle: "Find the Gaps Before the Attackers Do.",
    heroSubtext:
      "Delivered in partnership with Wattlecorp Cybersecurity Labs — advanced penetration testing and real-world attacker simulation engineered to uncover exploitable vulnerabilities across your entire attack surface.",
    overview: [
      "Vulnerability scans tell you what might be exposed. Penetration testing tells you what can actually be exploited. Fortress, in partnership with Wattlecorp Cybersecurity Labs, delivers offensive security engagements that simulate real-world attackers — targeting your web applications, APIs, network infrastructure, and cloud environments with the same techniques used by advanced threat actors.",
      "Every engagement is scoped and led by senior Fortress advisors and executed by Wattlecorp's specialist offensive security team. Findings are not just documented — they are validated, contextualized within your business risk environment, and accompanied by a remediation roadmap that your teams can actually act on.",
      "Our testing methodology is aligned to OWASP, PTES, and NIST standards. We do not run automated scans and call it penetration testing. Every engagement involves manual exploitation attempts, attack-path validation, and adversarial simulation designed to reflect the tactics, techniques, and procedures of real threat actors relevant to your sector.",
      "Post-engagement, we support your teams through the remediation process — including retesting to validate that identified vulnerabilities have been effectively resolved. Our goal is not just to find the gaps — it is to ensure they are closed.",
    ],
    capabilities: [
      "Web, mobile, and API penetration testing",
      "External and internal network security assessments",
      "Cloud infrastructure vulnerability analysis",
      "Red team and adversarial simulation exercises",
      "Manual exploitation and attack-path validation",
      "Remediation guidance and prioritized fixing",
      "Retesting and remediation validation",
      "Social engineering simulation (where scoped)",
    ],
    approach: [
      {
        title: "Scope & Plan",
        description:
          "We define the engagement scope with your team: target systems, testing boundaries, rules of engagement, and success criteria. Senior Fortress advisors align the testing plan to your business risk priorities.",
      },
      {
        title: "Test & Exploit",
        description:
          "Wattlecorp's offensive security specialists execute the engagement — combining automated tooling with manual exploitation techniques to identify and validate real, exploitable vulnerabilities across your attack surface.",
      },
      {
        title: "Report, Remediate & Retest",
        description:
          "We deliver a detailed findings report with severity ratings, exploitation evidence, and a prioritized remediation roadmap. We support your team through remediation and conduct retesting to confirm vulnerabilities are resolved.",
      },
    ],
    deliverables: [
      {
        title: "Penetration Test Report",
        description:
          "A full technical report documenting all identified vulnerabilities, exploitation evidence, attack paths, severity ratings (CVSS-aligned), and business impact context — written for both technical teams and executive reviewers.",
      },
      {
        title: "Executive Risk Summary",
        description:
          "A concise, non-technical summary of findings for board and executive audiences, translating technical vulnerabilities into business risk language with clear remediation priorities.",
      },
      {
        title: "Prioritized Remediation Roadmap",
        description:
          "A structured, actionable remediation plan organizing findings by severity and business impact, with recommended fixes, responsible parties, and target timelines.",
      },
      {
        title: "Retest Validation Report",
        description:
          "A post-remediation retesting report confirming which vulnerabilities have been resolved, which remain open, and any new findings identified during the validation engagement.",
      },
    ],
    audiences: [
      {
        description:
          "CISOs and technology leaders at enterprises handling sensitive customer data, financial transactions, or critical infrastructure who need independent, expert validation that their controls hold up against real-world attack techniques — not just compliance checkbox testing.",
      },
      {
        description:
          "Product and engineering leaders at technology companies, fintechs, or SaaS providers who need rigorous security testing of web applications and APIs before launch, after major releases, or as part of a continuous security assurance program.",
      },
      {
        description:
          "Boards and executive teams at organizations that have invested heavily in security infrastructure and want objective, adversarial validation that the investment is delivering real protection — not assumed protection.",
      },
    ],
    differentiators: [
      {
        title: "Senior Advisory + Specialist Execution",
        description:
          "Fortress provides strategic oversight and business risk context. Wattlecorp provides elite offensive security execution. The combination delivers findings that are both technically rigorous and business-relevant.",
      },
      {
        title: "Manual-First Methodology",
        description:
          "Real attackers don't rely on automated scanners. Neither do we. Every engagement prioritizes manual exploitation and creative attack-path validation.",
      },
      {
        title: "End-to-End Accountability",
        description:
          "We don't hand you a report and walk away. We support remediation, answer questions, and retest — ensuring vulnerabilities are actually resolved, not just documented.",
      },
    ],
    relatedSlugs: ["cyber-risk", "grc", "incident-advisory"],
    engagementSteps: [
      {
        title: "Discovery Meeting",
        bullets: [
          "Stakeholder Interviews",
          "Mission Objectives",
          "Asset Identification",
          "Scope Definition",
        ],
        description:
          "We begin every engagement by understanding your environment, your priorities, and your constraints — ensuring the work we do is aligned to what matters most to your organization.",
      },
      {
        title: "Strategic Assessment",
        bullets: [
          "Maturity Review",
          "Governance Evaluation",
          "Capability Analysis",
          "Compliance Assessment",
        ],
        description:
          "We assess your current security maturity, governance posture, and capability gaps against the relevant framework or threat model before any testing or advisory work begins.",
      },
      {
        title: "Risk Analysis",
        bullets: [
          "Threat Assessment",
          "Vulnerability Review",
          "Risk Prioritization",
          "Impact Analysis",
        ],
        description:
          "Findings from the assessment phase are scored and prioritized by business impact — giving your team a clear view of where the greatest exposures lie and what to address first.",
      },
      {
        title: "Advisory Roadmap",
        bullets: [
          "Strategic Recommendations",
          "Mitigation Plan",
          "Implementation Timeline",
          "Executive Reporting",
        ],
        description:
          "We translate risk analysis into a structured advisory roadmap with clear recommendations, a phased implementation plan, and executive-ready reporting.",
      },
      {
        title: "Implementation Support",
        bullets: [
          "Program Oversight",
          "Control Deployment",
          "Change Management",
          "Progress Tracking",
        ],
        description:
          "Our advisors remain engaged through implementation — providing oversight, supporting control deployment, and tracking progress against the remediation roadmap.",
      },
      {
        title: "Continuous Monitoring",
        bullets: [
          "Threat Intelligence",
          "Risk Monitoring",
          "Compliance Tracking",
          "Continuous Improvement",
        ],
        description:
          "Post-implementation, we establish ongoing monitoring to track the threat landscape, measure control effectiveness, and ensure your security posture continues to improve over time.",
      },
    ],
  },
};

export const Route = createFileRoute("/services/$slug")({
  head: ({ params }) => {
    const meta = SERVICES.find((s) => s.slug === params.slug);
    const title = meta
      ? `${meta.name} — Fortress Consulting`
      : "Service — Fortress Consulting";
    const description = meta?.blurb ?? "Fortress Consulting service.";
    return {
      meta: [
        { title },
        { name: "description", content: description },
        { property: "og:title", content: title },
        { property: "og:description", content: description },
      ],
    };
  },
  loader: ({ params }) => {
    if (!PAGES[params.slug]) throw notFound();
    return null;
  },
  component: ServiceSlugPage,
  notFoundComponent: () => (
    <div className="container-x pt-40 pb-24">
      <p className="eyebrow mb-4">404</p>
      <h1 className="text-3xl font-semibold">Service not found</h1>
    </div>
  ),
  errorComponent: ({ error }) => (
    <div className="container-x pt-40 pb-24">
      <p className="eyebrow mb-4">Error</p>
      <h1 className="text-3xl font-semibold">{error.message}</h1>
    </div>
  ),
});

function ServiceSlugPage() {
  const { slug } = Route.useParams();
  const data = PAGES[slug];
  if (!data) return null;
  return <ServicePage data={data} />;
}
